apiVersion: opentelemetry.io/v1alpha1
kind: Instrumentation
metadata:
  name: python-instrumentation
  namespace: myapp
spec:
  propagators:
    - tracecontext
    - baggage
  python:
    env:
      - name: OTEL_METRICS_EXPORTER
        value: prometheus
      - name: OTEL_EXPORTER_PROMETHEUS_PORT
        value: "9464"
      - name: OTEL_EXPORTER_PROMETHEUS_HOST
        value: "0.0.0.0"
      - name: OTEL_TRACES_EXPORTER
        value: none
      - name: OTEL_LOGS_EXPORTER
        value: none
  resource:
    resourceAttributes:
      service.name: agui-server
      service.namespace: myapp
      deployment.environment: production
