apiVersion: opentelemetry.io/v1alpha1
kind: Instrumentation
metadata:
  name: python-instrumentation
  namespace: myapp
spec:
  exporter:
    endpoint: http://otel-collector-collector.opentelemetry-operator-system.svc.cluster.local:4318
  propagators:
    - tracecontext
    - baggage
  python:
    env:
      - name: OTEL_METRICS_EXPORTER
        value: otlp
      - name: OTEL_TRACES_EXPORTER
        value: none
      - name: OTEL_LOGS_EXPORTER
        value: none
  resource:
    resourceAttributes:
      service.name: agui-server
      service.namespace: myapp
      deployment.environment: production
